# Generated by Django 4.0.3 on 2022-05-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='addreses',
            field=models.CharField(max_length=150, verbose_name='Dirección'),
        ),
    ]
