# Generated by Django 4.0.3 on 2022-05-10 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_rename_feeding_pets_alimentacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adopcion', '0002_alter_adoption_addreses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='otherPets',
            field=models.IntegerField(blank=True, verbose_name='Otras Mascotas'),
        ),
        migrations.CreateModel(
            name='HistoricalAdoption',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('user', models.CharField(max_length=150, verbose_name='Usuario')),
                ('firstName', models.CharField(max_length=150, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Número de Telefono')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('addreses', models.CharField(max_length=150, verbose_name='Dirección')),
                ('reason', models.CharField(max_length=150, verbose_name='Motivo para adoptar')),
                ('otherPets', models.IntegerField(blank=True, verbose_name='Otras Mascotas')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Pet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mascota.pets', verbose_name='Mascota')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical adoption',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
