version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=proyectorefugio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data

  django_app: 
    build: .
    environment:
      - DB_HOST=db
      - DB_NAME=proyectorefugio
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - .:/code
      - static:/code/Proyecto/static
      - media:/code/Proyecto/media
      - datos:/code/Proyecto/media/datos
      - pet_pics:/code/Proyecto/media/pet_pics
      - profile_pics:/code/Proyecto/media/profile_pics  
    depends_on: 
      - db

  nginx:
    image: nginx:1.20
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/Proyecto/static
      - media:/code/Proyecto/media
      - datos:/code/Proyecto/media/datos
      - pet_pics:/code/Proyecto/media/pet_pics
      - profile_pics:/code/Proyecto/media/profile_pics  
    depends_on:
      - django_app


volumes:
  .:
  postgres_data:
  static:
  media:
  datos:
  pet_pics:
  profile_pics: