# Generated by Django 4.0.3 on 2022-04-22 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50, verbose_name='Especie')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('sex', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=20, verbose_name='Sexo')),
                ('breed', models.CharField(max_length=50, verbose_name='Raza')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('vaccination', models.CharField(max_length=50, verbose_name='Vacunacion')),
                ('illness', models.CharField(max_length=150, verbose_name='Enfermedades')),
                ('feeding', models.CharField(max_length=150, verbose_name='Alimentacion')),
                ('rescue_date', models.DateField(verbose_name='Fecha de Rescate')),
                ('description', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('image', models.ImageField(default='pet.jpg', upload_to='pet_pics', verbose_name='Foto')),
                ('adopter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Adoptante')),
            ],
        ),
    ]
