# Generated by Django 4.0.3 on 2022-05-10 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pets',
            old_name='feeding',
            new_name='alimentacion',
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='age',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='illness',
            new_name='enfermedades',
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='species',
            new_name='especie',
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='breed',
            new_name='raza',
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='rescue_date',
            new_name='rescate',
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='sex',
            new_name='sexo',
        ),
        migrations.RemoveField(
            model_name='pets',
            name='vaccination',
        ),
        migrations.AddField(
            model_name='pets',
            name='vacuna',
            field=models.ManyToManyField(to='mascota.vacuna'),
        ),
        migrations.CreateModel(
            name='HistoricalVacuna',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vacuna',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPets',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('especie', models.CharField(max_length=50, verbose_name='Especie')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=20, verbose_name='Sexo')),
                ('raza', models.CharField(max_length=50, verbose_name='Raza')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('enfermedades', models.CharField(max_length=150, verbose_name='Enfermedades')),
                ('alimentacion', models.CharField(max_length=150, verbose_name='Alimentacion')),
                ('rescate', models.DateField(verbose_name='Fecha de Rescate')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('image', models.TextField(default='pet.jpg', max_length=100, verbose_name='Foto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('adopter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Adoptante')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
